### PR TITLE
fix FilePath relative directory

### PR DESCRIPTION
**Pull request by maa**

### CODE REVIEW

**Comment by iloktionov** [comment]
What's the motivation behind this PR? `Environment.CurrentDirectory` base was [intentionally replaced](https://github.com/vostok/logging.file/commit/3764e94a999cc31e534cecb11ff64bb4e089048e) with `AppDomain.CurrentDomain.BaseDirectory` in order to reduce user confusion when launching in environments such as IIS Express or R# test runner where these two directories are different by default.

**Comment by maa** [comment]
https://github.com/vostok/logging.file/blob/master/Vostok.Logging.File/Configuration/FileLogSettings.cs#L29
Plus, I cannot change `AppDomain.CurrentDomain.BaseDirectory` in contrast to `Environment.CurrentDirectory`.

**Comment by iloktionov** [comment]
[Fixed the stale xml-doc](https://github.com/vostok/logging.file/commit/7ab595d234d17a54deae8307b58d4ebba5964860), thanks for pointing it out.

> Plus, I cannot change AppDomain.CurrentDomain.BaseDirectory in contrast to Environment.CurrentDirectory.

You can always provide an absolute path though.

**Comment by maa** [comment]
Ok, thanks!

**Comment by iloktionov** [comment]
Okay, closing it then :)

**Pull request closed without merging**
